name: End-to-end Tests 🧪

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint

  chrome:
    needs: eslint
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run end-to-end tests on desktop 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}
        with:
          command: npm run test:cloud
          browser: chrome

  firefox:
    needs: eslint
    runs-on: ubuntu-22.04
    name: E2E on Firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run end-to-end tests on desktop 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}
        with:
          command: npm run test:cloud
          browser: firefox

  edge:
    needs: eslint
    runs-on: ubuntu-22.04
    name: E2E on Edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run end-to-end tests on desktop 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}
        with:
          command: npm run test:cloud
          browser: edge

  safari:
    needs: eslint
    runs-on: ubuntu-22.04
    name: E2E on Safari
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install webkit dependencies on Linux
        run: npx playwright install-deps webkit
      - name: Run end-to-end tests on desktop 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}
        with:
          command: npm run test:cloud --browser webkit